services:
  dockge-website:
    image: php:8.1-apache
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    command: bash -c "a2enmod rewrite remoteip && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && apache2-foreground"
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
x-dockge:
  urls:
    - https://dockge.kuma.pet
networks: {}
